chore(pipeline): tag updates

diff --git a/.tekton/monitoring-controller.yaml b/.tekton/monitoring-controller.yaml
--- a/.tekton/monitoring-controller.yaml
+++ b/.tekton/monitoring-controller.yaml
@@ -152,16 +152,20 @@ spec:
                   GIT_SHA=$(gh pr view $GIT_PR --repo $(params.git-url) --json headRefOid --jq .headRefOid)
 
                   export REPO=$(grep "export KO_DOCKER_REPO" Makefile | cut -d= -f2)
-                  export PR_TAG="pr-${GIT_PR}-${GIT_SHA}"
-                  export NEW_TAG=$(date -u +"%Y.%m.%d.%H%M%S")-pr${GIT_PR}
+                  export PR_TAG=$(skopeo list-tags docker://${REPO} | jq -r '.Tags[]' | grep -E ".*-pr-${GIT_PR}-${GIT_SHA}$" | sort -r | head -n 1)
+                  if [ -z "${PR_TAG}" ]; then
+                    echo "Failed to find PR tag for ${GIT_PR}-${GIT_SHA}"
+                    exit 1
+                  fi
+                  export NEW_TAG=$(date -u +"%Y.%m.%d.%H%M%S")-push-${GIT_PR} #-$(params.revision)
 
                   echo "Promoting ${REPO}:${PR_TAG} to ${REPO}:${NEW_TAG}"
-                  skopeo copy docker://${REPO}:${PR_TAG} docker://${REPO}:${NEW_TAG} --all --preserve-digests
+                  skopeo copy docker://${REPO}:${PR_TAG} docker://${REPO}:${NEW_TAG} --multi-arch all --preserve-digests
                   echo "${REPO}:${NEW_TAG}" > ${WORKSPACE_RESULTS_PATH}
                 else
                   GIT_PR=$(params.pull-request-number)
                   GIT_SHA=$(params.revision)
-                  export TAG="pr-${GIT_PR}-${GIT_SHA}"
+                  export TAG="$(date -u +"%Y.%m.%d.%H%M%S")-pr-${GIT_PR}-${GIT_SHA}"
                   make ko-build-pipeline
                 fi
 
